site_name: CloudSec.Cybr
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: light blue
  font:
    text: Roboto
  language: en
  features: 
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
  icon:
    annotation: material/plus-circle
      
plugins:
  - search
  - social
  - tags
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/christophelimpalair/
    - icon: fontawesome/brands/discord
      link: https://cybr.com/discord
copyright: Copyright &copy; 2024 Cybr, Inc.
markdown_extensions:
  - md_in_html
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      guess_lang: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css

nav:
  - Home: 'index.md'
  - 'AWS Security':
    - 'AWS Security Services': 'aws/aws-native-security-services.md'
    - 'IAM':
      - 'About IAM': 'aws/iam/about-iam.md'
      - 'Identity Center': 'aws/iam/identity-center.md'
      - 'Roles': 'aws/iam/roles.md'
      - 'Achieve Least Privilege': 'aws/iam/least-privilege.md'
      - 'Getting rid of access keys': 'aws/iam/get-rid-of-access-keys.md'
      - 'Open Source Tools': 'aws/iam/open-source-tools.md'
    - 'Incident Response':
      - 'Real World Case Studies': 'aws/incident-response/real-world-case-studies.md'
      - 'Stolen Credentials Playbook': 'aws/incident-response/stolen-credentials-playbook.md'
      - 'Cryptomining Playbook': 'aws/incident-response/cryptomining-playbook.md'
      - 'Open Source Tools': 'aws/incident-response/open-source-tools.md'
    - 'Monitoring & Logging':
      - 'AWS-Native Services': 'aws/monitoring-and-logging/aws-native-services.md'
      - 'Open Source Tools': 'aws/monitoring-and-logging/open-source-tools.md'
    - 'Threat Detection':
      - 'About Threat Detection': 'aws/threat-detection/threat-detection.md'
      - 'Guard Duty': 'aws/threat-detection/guard-duty.md'
      - 'Threat Databases': 'aws/threat-detection/threat-databases.md'
    - 'Security Assessments':
      - 'Pentesting & Red Teaming': 
        - 'Open Source Tools': 'aws/security-assessments/pentesting-red-teaming/open-source-tools.md'
        - 'Enumeration':
          - 'IAM': 'aws/security-assessments/pentesting-red-teaming/enumeration/iam-enumeration.md'
          - 'Secrets Manager': 'aws/security-assessments/pentesting-red-teaming/enumeration/secrets-manager-enumeration.md'
          - 'S3 Enumeration': 'aws/security-assessments/pentesting-red-teaming/enumeration/s3-enumeration.md'
        - 'Privilege Escalation':
          - 'IAM PrivEsc': 'aws/security-assessments/pentesting-red-teaming/privilege-escalation/iam-privilege-escalation.md'
      - 'Audits and Compliance': 'aws/security-assessments/audit-and-compliance.md'
    - 'Certifications': 
      - 'Certified Security Specialty': 'aws/certifications/certified-security-specialty.md'
    - 'Latest AWS Security News': 'aws/latest-news.md'
    - 'Sources': 'aws/sources.md'
  - 'Azure Security': azure/about-azure.md
  - 'Google Cloud Security': google-cloud/about-google-cloud.md
  - 'Career Paths': 'career-paths/cloudsec-career-paths.md'
  - About:
    - 'About': 'about.md'
    - 'License': 'license.md'
    - 'Contributing': 'contributing.md'
  - Sponsors: 'sponsors.md'
    
repo_name: CloudSec
repo_url: https://github.com/christophelimpalair/CloudSec
site_url: https://cloudsec.cybr.com